apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.service.name }}
    meta.helm.sh/release-namespace: {{  .Values.namespace  }}
  labels:
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
    helm.sh/chart: {{ .Values.service.name }}-{{ .Values.service.image.tag }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.service.name }}
      app.kubernetes.io/name: {{ .Values.service.name }}
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      port: http
